# Generated by Django 5.1.6 on 2025-08-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('photo', models.FilePathField()),
                ('time_create', models.TimeField()),
                ('name_slug', models.SlugField()),
            ],
        ),
    ]
