# Generated by Django 5.1.6 on 2025-08-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='photo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='time_create',
            field=models.CharField(),
        ),
    ]
