# Generated by Django 5.1.6 on 2025-08-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_music_photo_alter_music_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='name_slug',
            field=models.SlugField(unique=True),
        ),
    ]
