# Generated by Django 5.1.6 on 2025-10-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_music_name_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='quantity_ocenok',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='music',
            name='sum_ocenok',
            field=models.IntegerField(default=0),
        ),
    ]
